version: '3'

volumes:
    DATABASE:

services:
    api:
        build:
            context: ./
        ports:
            - "5000"
        volumes:
            - DATABASE:/home

    load-balancer:
        image: nginx:latest
        depends_on:
            - api
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
